console.log('8-square.js Missing size')
console.log('8-square.js School Missing size')
console.log('8-square.js 2 XX XX')
console.log('8-square.js 6 XXXXXX XXXXXX XXXXXX XXXXXX XXXXXX XXXXXX')
console.log('8-square.js -3')
